//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entieties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktura()
        {
            this.Produkty_w_Dokumentach = new HashSet<Produkty_w_Dokumentach>();
            this.Pozycja_Faktury = new HashSet<Pozycja_Faktury>();
        }
    
        public int IdFaktury { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public string NrFaktury { get; set; }
        public Nullable<System.DateTime> DataWystawienia { get; set; }
        public Nullable<System.DateTime> TerminPlatnosci { get; set; }
        public Nullable<int> IdPlatnosci { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public string NazwaProduktu { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public Nullable<int> Ilosc { get; set; }
        public Nullable<int> Rabat { get; set; }
        public Nullable<int> Marza { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Sposob_Platnosci Sposob_Platnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkty_w_Dokumentach> Produkty_w_Dokumentach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pozycja_Faktury> Pozycja_Faktury { get; set; }
    }
}
