//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entieties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia
    {
        public int IdHistorii { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<int> KategoriaHistorii { get; set; }
        public string Opis { get; set; }
        public string Dodajacy { get; set; }
        public bool CzyAktywny { get; set; }
    
        public virtual Kartoteka_Osobowa Kartoteka_Osobowa { get; set; }
        public virtual KategoriaHistorii KategoriaHistorii1 { get; set; }
    }
}
