//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entieties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kartoteka_Osobowa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kartoteka_Osobowa()
        {
            this.Badania_Lekarskie = new HashSet<Badania_Lekarskie>();
            this.Historia = new HashSet<Historia>();
            this.Karta_Pracy = new HashSet<Karta_Pracy>();
            this.Szkolenia_Okresowe = new HashSet<Szkolenia_Okresowe>();
            this.Wnioski_Urlopowe = new HashSet<Wnioski_Urlopowe>();
        }
    
        public int IdPracownika { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<decimal> Pesel { get; set; }
        public Nullable<System.DateTime> ZatrudnionyOd { get; set; }
        public Nullable<System.DateTime> ZatrudnionyDo { get; set; }
        public Nullable<System.DateTime> DataRozwiazania { get; set; }
        public Nullable<System.DateTime> WaznoscUbezpieczenia { get; set; }
        public Nullable<System.DateTime> WaznoscBadania { get; set; }
        public string Stanowisko { get; set; }
        public Nullable<int> IdOddzialu { get; set; }
        public string Plec { get; set; }
        public Nullable<int> DniUrlopu { get; set; }
        public Nullable<decimal> Stawka { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Badania_Lekarskie> Badania_Lekarskie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historia> Historia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karta_Pracy> Karta_Pracy { get; set; }
        public virtual Oddzialy Oddzialy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szkolenia_Okresowe> Szkolenia_Okresowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wnioski_Urlopowe> Wnioski_Urlopowe { get; set; }
    }
}
