//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entieties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oddzialy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oddzialy()
        {
            this.Kartoteka_Osobowa = new HashSet<Kartoteka_Osobowa>();
        }
    
        public int IdOddzialu { get; set; }
        public string NazwaOddzialu { get; set; }
        public Nullable<bool> Czyaktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kartoteka_Osobowa> Kartoteka_Osobowa { get; set; }
    }
}
